version: '3'

services:
  api:
    build:
      context: ./api
    container_name: node_webapp_api
    ports:
    - 3000:3000
    volumes:
    - ./api:/var/app/:rw,cached
    command: >
      sh -c '
      npm install &&
      npm run start:dev
      '
