version: '3'

services:
  api:
    build:
      context: ./api
    container_name: node_webapp_api
    ports:
    - 3000:3000
    volumes:
    - ./api:/var/app/:rw,cached
    command: >
      sh -c '
      npm install &&
      npm run start:dev
      '
  postgres:
     container_name: node_webapp_postgres
     image: postgres
     environment:
       POSTGRES_USER: ${DB_USER:-postgres}
       POSTGRES_PASSWORD: ${DB_PASS:-postgres}
       PGDATA: /data/postgres
     volumes:
     - postgres:/data/postgres
     - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
     ports:
       - 5432:5432

  migration:
     image: node_webapp_api:latest
     command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "migrate"]
     depends_on:
     - postgres
volumes:
  postgres:
